const reasons = [
    ["Zamrzlá vyhýbka", 10],
    ["Ztráta lopatky na uhlí", 10],
    ["Srážka s jelenem", 7],
    ["Želva na kolejích", 5],
    ["Strojvedoucí pod vlivem", 10],
    ["Spadlý strom na kolejích", 10],
    ["Práce na železnici", 15],
    ["Čekání na přípoj", 10],
    ["Špinavé čelní sklo", 10],
    ["Nedostatek finančních prostředků", 12],
    ["Nedostatečný zůstatek kreditu strojvedoucího", 10],
    ["Zaseklé závory", 10],
    ["Drezura na trati", 10],
    ["Vískání mastných vlasů topiči", 10],
    ["Změna rozchodu kolejí", 10],
    ["Srážka s mouchou", 10],
    ["Výluka", 100],
    ["Zpoždění vzniklé na území cizího státu", 50],
    ["Přepadení vlaku", 10],
    ["Výpadek elektřiny", 10],
    ["Zatažení za záchrannou brzdu", 20],
    ["Cestující v kolejišti", 10],
    ["Porucha dveří", 10],
    ["Upadlé kolo", 10],
    ["Porucha stěračů", 10],
    ["Nepřítomnost strojvedoucího", 20],
    ["Porucha klimatizace", 10],
    ["Porucha rozhlasu", 10],
    ["Ošoupané brzdné destičky", 10],
    ["Závada na přejezdu", 10],
    ["Neznámý důvod", 150],
    ["Červená na semaforu", 10],
    ["Kozel a rudé tričko na trati", 10],
    ["Spadlé vedení", 10],
    ["Ukradené kabely", 10],
    ["Nefunkční trolej", 10],
    ["Vykolejení vlaku", 10],
    ["Povodeň", 10],
    ["Důchodce na přejezdu", 10],
    ["Špatná orientace lokomotivy", 10],
    ["Porucha a výměna lokomotivy", 10],
    ["Omezená rychlost", 30],
    ["Omezení na trati", 60],
    ["Jazyková bariéra", 5],
    ["Výpadek Wi-Fi", 10],
    ["Policejní vyšetřování", 10],
    ["Topící se personál", 10],
    ["Neznalost trasy strojvedoucím", 10],
    ["Výslech strojvedoucího", 10],
    ["Vysoký počet cestujících", 4],
    ["Nízký počet cestujících", 10],
    ["Plně obsazený vůz", 10],
    ["Zaučování kuchaře v jídelním voze", 10],
    ["Historická jízda", 10],
    ["Nedostatek uhlí", 10],
    ["Nedostatek páry", 10],
    ["Fronta na benzínové pumpě", 10],
    ["Kolona", 10],
    ["Zataženo", 10],
    ["Déšť", 80],
    ["Spadlý most", 10],
    ["Špatné počasí", 10],
    ["Nedostatečné osvětlení v tunelu", 10],
    ["Rozbité okno", 10],
    ["Ztráta vlakové soupravy", 10],
    ["Objízdná trasa", 20],
    ["Stávka zaměstnanců drah", 10],
    ["Výpadek signálu GPS", 10],
    ["Úklid vlaku", 40],
    ["Výměna žárovky", 10],
    ["Zapomenutá svačina v depu", 10],
    ["Roj včel v kabině", 5],
    ["Hustá mlha", 10],
    ["Mlha", 20],
    ["Sklon trati", 10],
    ["Připalené jídlo v jídelním voze", 10],
    ["Půdní sesuv", 10],
    ["Úder blesku do soupravy", 10],
    ["Zpoždění vlaku", 50],
    ["Pomalá jízda", 50],
    ["Úder meteoritu", 10],
    ["Náhlá změna jizdního řádu", 30],
    ["Neznámý předmět v pantografu", 10],
    ["Hraniční kontrola", 10],
    ["Přednost vlaku s vyšší prioritou", 25]
]