const reasons = [
    ["Zamrzlá vyhýbka", 1],
    ["Ztráta lopatky na uhlí", 1],
    ["Srážka s jelenem", 1],
    ["Želva na kolejích", 1],
    ["Strojvedoucí pod vlivem", 1],
    ["Spadlý strom na kolejích", 1],
    ["Práce na železnici", 1],
    ["Čekání na přípoj", 1],
    ["Špinavé čelní sklo", 1],
    ["Nedostatek finančních prostředků", 1],
    ["Nedostatečný zůstatek kreditu strojvedoucího", 1],
    ["Zaseklé závory", 1],
    ["Drezura na trati", 1],
    ["Vískání mastných vlasů topiči", 1],
    ["Změna rozchodu kolejí", 1],
    ["Srážka s mouchou", 1],
    ["Výluka", 10],
    ["Zpoždění vzniklé na území cizího státu", 5],
    ["Přepadení vlaku", 1],
    ["Výpadek elektřiny", 1],
    ["Zatažení za záchrannou brzdu", 2],
    ["Cestující v kolejišti", 1],
    ["Porucha dveří", 1],
    ["Upadlé kolo", 1],
    ["Porucha stěračů", 1],
    ["Nepřítomnost strojvedoucího", 2],
    ["Porucha klimatizace", 1],
    ["Porucha rozhlasu", 1],
    ["Ošoupané brzdné destičky", 1],
    ["Závada na přejezdu", 1],
    ["Neznámý důvod", 15],
    ["Červená", 1],
    ["Kozel a rudé tričko na trati", 1],
    ["Spadlé vedení", 1],
    ["Ukradené kabely", 1],
    ["Nefunkční trolej", 1],
    ["Vykolejení vlaku", 1],
    ["Povodeň", 1],
    ["Důchodce na přejezdu", 1],
    ["Špatná orientace lokomotivy", 1],
    ["Porucha a výměna lokomotivy", 1],
    ["Omezená rychlost", 3],
    ["Omezení na trati", 6],
    ["Jazyková bariéra", 1],
    ["Výpadek Wi-Fi", 1],
    ["Policejní vyšetřování", 1],
    ["Topící se personál", 1],
    ["Neznalost trasy strojvedoucím", 1],
    ["Výslech strojvedoucího", 1],
    ["Vysoký počet cestujících", 4],
    ["Nízký počet cestujících", 1],
    ["Plně obsazený vůz", 1],
    ["Zaučování kuchaře v jídelním voze", 1],
    ["Historická jízda", 1],
    ["Nedostatek uhlí", 1],
    ["Nedostatek páry", 1],
    ["Fronta na benzínové pumpě", 1],
    ["Kolona", 1],
    ["Zataženo", 1],
    ["Déšť", 8],
    ["Spadlý most", 1],
    ["Špatné počasí", 1],
    ["Nedostatečné osvětlení v tunelu", 1],
    ["Rozbité okno", 1],
    ["Ztráta vlakové soupravy", 1],
    ["Objízdná trasa", 2],
    ["Stávka zaměstnanců drah", 1],
    ["Výpadek signálu GPS", 1],
    ["Úklid vlaku", 4],
    ["Výměna žárovky", 1],
    ["Zapomenutá svačina v depu", 1],
    ["Roj včel v kabině", 1],
    ["Hustá mlha", 1],
    ["Mlha", 2],
    ["Sklon trati", 1],
    ["Připalené jídlo v jídelním voze", 1],
    ["Půdní sesuv", 1],
    ["Úder blesku do soupravy", 1],
    ["Zpoždění vlaku", 5],
    ["Pomalá jízda", 5]
]