// 1 - extremely rare
// 2 - especially rare
const reasons = [
    ["Zamrzlá vyhýbka", 4],
    ["Ztráta lopatky na uhlí", 6],
    ["Srážka s jelenem", 7],
    ["Želva na kolejích", 5],
    ["Strojvedoucí pod vlivem", 17],
    ["Spadlý strom na kolejích", 10],
    ["Práce na železnici", 25],
    ["Čekání na přípoj", 40],
    ["Špinavé čelní sklo", 4],
    ["Nedostatek finančních prostředků", 12],
    ["Nedostatečný zůstatek kreditu strojvedoucího", 1],
    ["Zaseklé závory", 8],
    ["Drezura na trati", 3],
    ["Vískání mastných vlasů topiči", 9],
    ["Změna rozchodu kolejí", 5],
    ["Srážka s mouchou", 1],
    ["Výluka", 100],
    ["Zpoždění vzniklé na území cizího státu", 50],
    ["Přepadení vlaku", 2],
    ["Výpadek elektřiny", 20],
    ["Zatažení za záchrannou brzdu", 20],
    ["Cestující v kolejišti", 15],
    ["Porucha dveří", 10],
    ["Upadlé kolo", 2],
    ["Porucha stěračů", 2],
    ["Nepřítomnost strojvedoucího", 20],
    ["Porucha klimatizace", 8],
    ["Porucha rozhlasu", 8],
    ["Ošoupané brzdné destičky", 6],
    ["Závada na přejezdu", 15],
    ["Neznámý důvod", 150],
    ["Červená na semaforu", 10],
    ["Kozel a rudé tričko na trati", 1],
    ["Spadlé vedení", 7],
    ["Ukradené kabely", 15],
    ["Nefunkční trolej", 10],
    ["Vykolejení vlaku", 7],
    ["Povodeň", 3],
    ["Důchodce na přejezdu", 10],
    ["Špatná orientace lokomotivy", 10],
    ["Porucha a výměna lokomotivy", 10],
    ["Omezená rychlost", 30],
    ["Omezení na trati", 60],
    ["Jazyková bariéra", 5],
    ["Výpadek Wi-Fi", 10],
    ["Policejní vyšetřování", 4],
    ["Topící se personál", 3],
    ["Neznalost trasy strojvedoucím", 15],
    ["Výslech strojvedoucího", 2],
    ["Vysoký počet cestujících", 40],
    ["Nízký počet cestujících", 15],
    ["Plně obsazený vůz", 30],
    ["Zaučování kuchaře v jídelním voze", 4],
    ["Historická jízda", 10],
    ["Nedostatek uhlí", 4],
    ["Nedostatek páry", 4],
    ["Fronta na benzínové pumpě", 1],
    ["Kolona", 2],
    ["Zataženo", 15],
    ["Déšť", 80],
    ["Spadlý most", 2],
    ["Špatné počasí", 20],
    ["Nedostatečné osvětlení v tunelu", 5],
    ["Rozbité okno", 8],
    ["Ztráta vlakové soupravy", 4],
    ["Objízdná trasa", 20],
    ["Stávka zaměstnanců drah", 15],
    ["Výpadek signálu GPS", 7],
    ["Úklid vlaku", 40],
    ["Výměna žárovky", 2],
    ["Zapomenutá svačina v depu", 4],
    ["Roj včel v kabině", 5],
    ["Hustá mlha", 10],
    ["Mlha", 20],
    ["Sklon trati", 10],
    ["Připalené jídlo v jídelním voze", 7],
    ["Půdní sesuv", 4],
    ["Úder blesku do soupravy", 9],
    ["Zpoždění vlaku", 50],
    ["Pomalá jízda", 50],
    ["Úder meteoritu", 1],
    ["Náhlá změna jizdního řádu", 30],
    ["Neznámý předmět v pantografu", 3],
    ["Hraniční kontrola", 10],
    ["Přednost vlaku s vyšší prioritou", 25],
    ["Příjezd prezidenta", 1] // dát tam název země?
]