// Higher rarity values are selected more often; lower values represent rarer cargo.
const goods = Object.freeze([
    { name: "Chléb", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Rohlíky", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Housky", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Bagety", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Croissanty", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Mouka", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Cukr", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Sůl", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Rýže", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Těstoviny", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Ovesné vločky", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Brambory", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Cibule", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Česnek", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Mrkev", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Rajčata", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Papriky", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Okurky", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Jablka", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Hrušky", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Banány", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Pomeranče", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Citrony", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Jahody", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Borůvky", rarity: 5, category: "Potraviny a nápoje" },
    { name: "Mléko", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Máslo", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Sýr", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Jogurty", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Vejce", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Kuřecí maso", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Hovězí maso", rarity: 5, category: "Potraviny a nápoje" },
    { name: "Vepřové maso", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Ryby", rarity: 5, category: "Potraviny a nápoje" },
    { name: "Šunka", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Klobásy", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Konzervy", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Mražená zelenina", rarity: 5, category: "Potraviny a nápoje" },
    { name: "Zmrzlina", rarity: 5, category: "Potraviny a nápoje" },
    { name: "Čokoláda", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Sušenky", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Bonbony", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Brambůrky", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Oříšky", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Káva", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Čaj", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Minerální voda", rarity: 10, category: "Potraviny a nápoje" },
    { name: "Ovocné džusy", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Limonády", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Koření", rarity: 8, category: "Potraviny a nápoje" },
    { name: "Mobilní telefony", rarity: 4, category: "Elektronika" },
    { name: "Notebooky", rarity: 2, category: "Elektronika" },
    { name: "Tablety", rarity: 4, category: "Elektronika" },
    { name: "Stolní počítače", rarity: 2, category: "Elektronika" },
    { name: "Počítačové monitory", rarity: 4, category: "Elektronika" },
    { name: "Televizory", rarity: 2, category: "Elektronika" },
    { name: "Herní konzole", rarity: 2, category: "Elektronika" },
    { name: "Sluchátka", rarity: 4, category: "Elektronika" },
    { name: "Reproduktory", rarity: 4, category: "Elektronika" },
    { name: "Chytré hodinky", rarity: 4, category: "Elektronika" },
    { name: "Fotoaparáty", rarity: 2, category: "Elektronika" },
    { name: "Videokamery", rarity: 2, category: "Elektronika" },
    { name: "Tiskárny", rarity: 4, category: "Elektronika" },
    { name: "Wi-Fi routery", rarity: 4, category: "Elektronika" },
    { name: "Pevné disky", rarity: 4, category: "Elektronika" },
    { name: "USB flash disky", rarity: 8, category: "Elektronika" },
    { name: "Paměťové karty", rarity: 8, category: "Elektronika" },
    { name: "Nabíječky", rarity: 8, category: "Elektronika" },
    { name: "Baterie", rarity: 8, category: "Elektronika" },
    { name: "Prodlužovací kabely", rarity: 8, category: "Elektronika" },
    { name: "LED žárovky", rarity: 8, category: "Elektronika" },
    { name: "Elektrické konvice", rarity: 4, category: "Elektronika" },
    { name: "Mikrovlnné trouby", rarity: 4, category: "Elektronika" },
    { name: "Kávovary", rarity: 4, category: "Elektronika" },
    { name: "Mixéry", rarity: 4, category: "Elektronika" },
    { name: "Vysavače", rarity: 4, category: "Elektronika" },
    { name: "Žehličky", rarity: 4, category: "Elektronika" },
    { name: "Ventilátory", rarity: 4, category: "Elektronika" },
    { name: "Šicí stroje", rarity: 4, category: "Elektronika" },
    { name: "Toaletní papír", rarity: 10, category: "Domácnost" },
    { name: "Papírové kapesníky", rarity: 10, category: "Domácnost" },
    { name: "Kuchyňské utěrky", rarity: 10, category: "Domácnost" },
    { name: "Mýdlo", rarity: 10, category: "Domácnost" },
    { name: "Šampony", rarity: 10, category: "Domácnost" },
    { name: "Zubní pasty", rarity: 10, category: "Domácnost" },
    { name: "Zubní kartáčky", rarity: 10, category: "Domácnost" },
    { name: "Prací prášek", rarity: 10, category: "Domácnost" },
    { name: "Aviváž", rarity: 8, category: "Domácnost" },
    { name: "Prostředek na nádobí", rarity: 10, category: "Domácnost" },
    { name: "Čisticí prostředky", rarity: 8, category: "Domácnost" },
    { name: "Odpadkové pytle", rarity: 10, category: "Domácnost" },
    { name: "Houbičky na nádobí", rarity: 10, category: "Domácnost" },
    { name: "Svíčky", rarity: 8, category: "Domácnost" },
    { name: "Zápalky", rarity: 8, category: "Domácnost" },
    { name: "Deštníky", rarity: 8, category: "Domácnost" },
    { name: "Ručníky", rarity: 8, category: "Domácnost" },
    { name: "Ložní prádlo", rarity: 8, category: "Domácnost" },
    { name: "Polštáře", rarity: 8, category: "Domácnost" },
    { name: "Přikrývky", rarity: 8, category: "Domácnost" },
    { name: "Ramínka na oblečení", rarity: 8, category: "Domácnost" },
    { name: "Trička", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Košile", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Kalhoty", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Mikiny", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Bundy", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Ponožky", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Spodní prádlo", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Boty", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Čepice", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Rukavice", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Batohy", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Kufry", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Peněženky", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Brýle", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Hodinky", rarity: 6, category: "Oblečení a osobní věci" },
    { name: "Knihy", rarity: 7, category: "Kancelář a knihy" },
    { name: "Časopisy", rarity: 7, category: "Kancelář a knihy" },
    { name: "Sešity", rarity: 9, category: "Kancelář a knihy" },
    { name: "Kancelářský papír", rarity: 9, category: "Kancelář a knihy" },
    { name: "Obálky", rarity: 9, category: "Kancelář a knihy" },
    { name: "Propisky", rarity: 9, category: "Kancelář a knihy" },
    { name: "Tužky", rarity: 9, category: "Kancelář a knihy" },
    { name: "Pastelky", rarity: 7, category: "Kancelář a knihy" },
    { name: "Fixy", rarity: 7, category: "Kancelář a knihy" },
    { name: "Lepicí pásky", rarity: 9, category: "Kancelář a knihy" },
    { name: "Nůžky", rarity: 7, category: "Kancelář a knihy" },
    { name: "Kalkulačky", rarity: 7, category: "Kancelář a knihy" },
    { name: "Stolní lampy", rarity: 7, category: "Kancelář a knihy" },
    { name: "Židle", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Malé stolky", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Police", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Květináče", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Pokojové rostliny", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Zahradní nářadí", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Kladiva", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Šroubováky", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Vrtačky", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Sady šroubů", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Měřicí pásma", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Pracovní rukavice", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Barvy na zeď", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Štětce", rarity: 5, category: "Dům, zahrada a nářadí" },
    { name: "Jízdní kola", rarity: 3, category: "Sport a volný čas" },
    { name: "Koloběžky", rarity: 4, category: "Sport a volný čas" },
    { name: "Fotbalové míče", rarity: 4, category: "Sport a volný čas" },
    { name: "Tenisové rakety", rarity: 4, category: "Sport a volný čas" },
    { name: "Činky", rarity: 4, category: "Sport a volný čas" },
    { name: "Karimatky", rarity: 4, category: "Sport a volný čas" },
    { name: "Stany", rarity: 4, category: "Sport a volný čas" },
    { name: "Spací pytle", rarity: 4, category: "Sport a volný čas" },
    { name: "Rybářské pruty", rarity: 4, category: "Sport a volný čas" },
    { name: "Deskové hry", rarity: 4, category: "Sport a volný čas" },
    { name: "Puzzle", rarity: 4, category: "Sport a volný čas" },
    { name: "Stavebnice", rarity: 4, category: "Sport a volný čas" },
    { name: "Plyšové hračky", rarity: 4, category: "Sport a volný čas" },
    { name: "Modely vláčků", rarity: 4, category: "Sport a volný čas" },
    { name: "Hudební nástroje", rarity: 2, category: "Sport a volný čas" },
    { name: "Krmivo pro psy", rarity: 4, category: "Sport a volný čas" },
    { name: "Krmivo pro kočky", rarity: 4, category: "Sport a volný čas" },
    { name: "Akvária", rarity: 3, category: "Zvířata, zdraví a bezpečnost" },
    { name: "Veterinární potřeby", rarity: 3, category: "Zvířata, zdraví a bezpečnost" },
    { name: "Lékárničky", rarity: 5, category: "Zvířata, zdraví a bezpečnost" },
    { name: "Obvazy", rarity: 5, category: "Zvířata, zdraví a bezpečnost" },
    { name: "Ochranné roušky", rarity: 5, category: "Zvířata, zdraví a bezpečnost" },
    { name: "Hasicí přístroje", rarity: 4, category: "Zvířata, zdraví a bezpečnost" },
    { name: "Autodíly", rarity: 3, category: "Zvířata, zdraví a bezpečnost" },
    { name: "Motorový olej", rarity: 5, category: "Zvířata, zdraví a bezpečnost" },
    { name: "Pneumatiky", rarity: 4, category: "Průmysl a speciální zásilky" },
    { name: "Dřevěné desky", rarity: 4, category: "Průmysl a speciální zásilky" },
    { name: "Keramické dlaždice", rarity: 4, category: "Průmysl a speciální zásilky" },
    { name: "Balíky sena", rarity: 3, category: "Průmysl a speciální zásilky" },
    { name: "Včelí med", rarity: 6, category: "Průmysl a speciální zásilky" },
    { name: "Poštovní zásilky", rarity: 8, category: "Průmysl a speciální zásilky" },
    { name: "Muzejní exponáty", rarity: 1, category: "Průmysl a speciální zásilky" },
    { name: "Filmové rekvizity", rarity: 2, category: "Průmysl a speciální zásilky" },
    { name: "Květinové kytice", rarity: 5, category: "Průmysl a speciální zásilky" },
    { name: "Narozeninové dorty", rarity: 4, category: "Průmysl a speciální zásilky" },
    { name: "Vánoční ozdoby", rarity: 4, category: "Průmysl a speciální zásilky" },
    { name: "Sportovní trofeje", rarity: 2, category: "Průmysl a speciální zásilky" },
    { name: "Laboratorní vzorky", rarity: 1, category: "Průmysl a speciální zásilky" },
    { name: "Náhradní díly pro vlaky", rarity: 1, category: "Průmysl a speciální zásilky" }
]);
