const SECONDS_PER_DAY = 86400;
const MILLISECONDS_PER_DAY = 86400000;

const TRANSPORT_TYPE = Object.freeze({
    STATION: 0,
    TRAIN: 1,
    WALKING: 2
});

const TRAIN_STATUS = Object.freeze({
    NOT_DEPARTED: 0,
    STOPPED_BEFORE_TARGET: 1,
    TRAVELLING_TO_TARGET: 2,
    STOPPED_AT_TARGET: 3,
    TRAVELLING_PAST_TARGET: 4,
    STOPPED_PAST_TARGET: 5,
    FINISHED: 6,
    CANCELLED_BEFORE_TARGET: -1,
    CANCELLED_AFTER_TARGET: 7
});
